#! /bin/sh
set -e

action=${1:-"default"}

if [ ! -e /var/service/mullvad ]; then
    echo "Mullvad service is unavailable."
    exit 1
fi

get_best() {
    trap true INT
    printf "Will now ping all servers, this may take a while. Press '^C' to interrupt.\n"
    mullvbest -q > /var/lib/mullvad/selected
    trap - INT
}

case $action in
    auto)
        if [ -e /var/service/mullvad/down ]; then
            echo "Automatically connect to VPN on boot."
            rm /var/service/mullvad/down
        else
            echo "Do not connect to VPN on boot."
            touch /var/service/mullvad/down
        fi
        ;;
    default)
        [ -r /var/lib/mullvad/selected ] || get_best
        ;;
    off)
        sv down mullvad
        exit
        ;;
    *)
        if [ ! -e "/etc/wireguard/mullvad-$action.conf" ]; then
            echo "/etc/wireguard/mullvad-$action.conf not found";
            exit 1
        fi
        echo "mullvad-$action" > /var/lib/mullvad/selected
        ;;
esac

sv down mullvad
sv up mullvad
