#! /bin/sh

print_usage() {
    printf "Usage: mullvbest [-q] [-f FILTER]\n"
}

filter=""

while getopts 'qf:' flag; do
    case $flag in
        q)
            quiet='true'
            ;;
        f)
            echo "filtering $OPTARG"
            filter=${OPTARG}
            ;;
        *)
            print_usage
            exit 1
            ;;
    esac
done

best=""
best_value=5000000

doping() {
    ping -qw 4 $1 | awk -F '/' 'END {sub(/\./,"",$5);print $5}'
}

report_and_exit() {
    if [ -z "$best" ]; then
        printf "fail: no results!\n" >&2
        exit 1
    fi
    if [ -n "$quiet" ]; then
        printf "$best\n"
    else
        printf "\nThe best result was $best ($best_value).\n"
    fi
    exit 0
}

trap report_and_exit INT

for conf in /etc/wireguard/mullvad-$filter*.conf; do
    [ -r "$conf" ] || continue
    server=$(printf "$conf" | awk -F '[-.]' '{print $2}')
    address=$(awk -F '[ :]' 'END {print $3}' $conf)
    [ -n "$quiet" ] || printf "pinging $server ($address)... "
    value=$(doping $address)
    [ -n "$quiet" ] || printf "$value\n"
    [ $value -lt $best_value ] && best_value=$value && best=$server
done

report_and_exit
